version: '3.7'
services:
  postgres:
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=micronaut
      - POSTGRES_USER=micronaut
      - POSTGRES_PASSWORD=micronaut
  demo:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - demo_demo
    ports:
    - "8256:8256"
    depends_on:
      - postgres
