micronaut:
  application:
    name: demo
  server:
    port: 8256

datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/micronaut'
    username: 'micronaut'
    password: 'micronaut'
    driverClassName: 'postgresql'
